Repository MicrosoftDocs/dataexplorer-docs, pull requests merged in 2020-06, with the labels that each got.

#127 Fixed table formatting bug in kusto-cli.md
  data-explorer/kusto/tools/kusto-cli.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#124 API-T-tdskl - edited
  data-explorer/kusto/api/tds/tdskql.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#128 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/customer-managed-keys-cli.md
  data-explorer/customer-managed-keys-csharp.md
  data-explorer/customer-managed-keys-portal.md
  data-explorer/customer-managed-keys-resource-manager.md
  data-explorer/ingest-data-streaming.md
  data-explorer/kusto/management/data-export/continuous-data-export.md
  data-explorer/kusto/management/data-export/export-data-to-an-external-table.md
  data-explorer/kusto/management/data-ingestion/eventgrid.md
  data-explorer/kusto/management/data-ingestion/ingest-inline.md
  data-explorer/kusto/management/diagnostics.md
  data-explorer/kusto/management/ingestiontimepolicy.md
  data-explorer/kusto/management/roworder-policy.md
  data-explorer/kusto/management/streamingingestion-policy.md
  data-explorer/kusto/management/streamingingestionpolicy.md
  data-explorer/kusto/query/mv-applyoperator.md
  data-explorer/kusto/query/schema-entities/externaltables.md
  data-explorer/kusto/tools/azure-data-factory.md
  data-explorer/kusto/tools/flow.md
  data-explorer/kusto/tools/index.md
  data-explorer/toc.yml
Labels: do-not-merge

#129 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#122 Follower: add explanation on roles
  data-explorer/follower.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, ready-to-merge

#130 Fix git push error for protected CLA branch
  data-explorer/kusto/management/alter-database.md
  data-explorer/kusto/management/data-ingestion/ingest-inline.md
  data-explorer/kusto/management/drop-ingestion-mapping-command.md
  data-explorer/kusto/management/journal.md
  data-explorer/kusto/management/operations.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/management/update-policy.md
  data-explorer/kusto/query/ipv4-comparefunction.md
  data-explorer/kusto/query/ipv4-is-matchfunction.md
  data-explorer/kusto/query/ipv6-comparefunction.md
  data-explorer/kusto/query/ipv6-is-matchfunction.md
  data-explorer/kusto/query/parse-ipv4-maskfunction.md
  data-explorer/kusto/query/parse-ipv4function.md
  data-explorer/kusto/query/parse-ipv6-maskfunction.md
  data-explorer/kusto/query/parse-ipv6function.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/topnestedoperator.md
  data-explorer/media/visualize-power-bi/search-get-data.png
  data-explorer/toc.yml
  data-explorer/visualize-power-bi.md
  data-explorer/viz-overview.md
Labels: do-not-merge

#131 Fix git push error for protected CLA branch
  data-explorer/kusto/query/arrayslicefunction.md
Labels: do-not-merge

#136 Fix git push error for protected CLA branch
  data-explorer/customer-managed-keys-cli.md
  data-explorer/customer-managed-keys-csharp.md
  data-explorer/customer-managed-keys-portal.md
  data-explorer/customer-managed-keys-powershell.md
  data-explorer/customer-managed-keys-resource-manager.md
  data-explorer/toc.yml
Labels: do-not-merge

#138 Fix git push error for protected CLA branch
  data-explorer/kusto/query/joinoperator.md
  data-explorer/kusto/query/mvexpandoperator.md
  data-explorer/kusto/query/samples.md
Labels: do-not-merge

#139 Fix git push error for protected CLA branch
  data-explorer/kusto/management/capacitypolicy.md
Labels: do-not-merge

#140 Fix a typo
  data-explorer/kusto/management/data-ingestion/ingest-from-query.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#141 Fix git push error for protected CLA branch
  data-explorer/kusto/api/tds/tdskql.md
  data-explorer/kusto/concepts/queryconsistency.md
  data-explorer/kusto/concepts/resulttruncation.md
  data-explorer/kusto/management/alter-table-docstring-command.md
  data-explorer/kusto/management/cachepolicy.md
  data-explorer/kusto/management/sandboxpolicy.md
  data-explorer/kusto/query/hll-merge-aggfunction.md
  data-explorer/kusto/query/ipv6-comparefunction.md
  data-explorer/kusto/query/parse-ipv4function.md
  data-explorer/kusto/query/parse-ipv6-maskfunction.md
  data-explorer/kusto/query/parse-ipv6function.md
  data-explorer/kusto/query/percentiles-aggfunction.md
  data-explorer/kusto/query/series-outliersfunction.md
  data-explorer/kusto/query/whereoperator.md
  data-explorer/kusto/tools/kusto-cli.md
Labels: do-not-merge

#143 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/anyif-aggfunction.md
  data-explorer/kusto/query/topnestedoperator.md
Labels: do-not-merge

#144 Fix git push error for protected CLA branch
  data-explorer/azure-data-explorer-dashboards.md
  data-explorer/dashboard-parameters.md
  data-explorer/media/dashboard-parameters/companies-side-pane.png
  data-explorer/media/dashboard-parameters/dashboard-icons.png
  data-explorer/media/dashboard-parameters/fixed-value-multiple.png
  data-explorer/media/dashboard-parameters/fixed-value-single.png
  data-explorer/media/dashboard-parameters/modify-parameter.png
  data-explorer/media/dashboard-parameters/new-parameter-button.png
  data-explorer/media/dashboard-parameters/properties.png
  data-explorer/media/dashboard-parameters/query-based-multiple.png
  data-explorer/media/dashboard-parameters/query-based-single.png
  data-explorer/media/dashboard-parameters/query-intellisense.png
  data-explorer/media/dashboard-parameters/select-companies.png
  data-explorer/media/dashboard-parameters/start-end-side-pane.png
  data-explorer/media/dashboard-parameters/time-range.png
  data-explorer/media/dashboard-parameters/top-five-repos.png
  data-explorer/toc.yml
Labels: do-not-merge

#147 Fix misspellings
  data-explorer/kusto/query/packfunction.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#149 Fix git push error for protected CLA branch
  data-explorer/kusto/query/autoclusterplugin.md
  data-explorer/kusto/query/base64_decode_toarrayfunction.md
  data-explorer/kusto/query/base64_encode_tostringfunction.md
  data-explorer/kusto/query/current-principalfunction.md
  data-explorer/kusto/query/isnotemptyfunction.md
  data-explorer/kusto/query/parsepathfunction.md
  data-explorer/kusto/query/serializeoperator.md
  data-explorer/kusto/query/series-decompose-forecastfunction.md
  data-explorer/kusto/query/series-fit-linefunction.md
  data-explorer/kusto/query/series-periods-validatefunction.md
  data-explorer/kusto/query/series-seasonalfunction.md
  data-explorer/kusto/query/strcatfunction.md
  data-explorer/kusto/query/summarizeoperator.md
  data-explorer/kusto/tools/kustowpa.md
  data-explorer/media/web-query-data/export-results.png
  data-explorer/media/web-query-data/pin-to-dashboard.png
  data-explorer/media/web-query-data/share-menu.png
  data-explorer/toc.yml
  data-explorer/web-query-data.md
Labels: do-not-merge

#150 Format syntax section for readability
  data-explorer/kusto/query/series-fit-2linesfunction.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#155 Fix git push error for protected CLA branch
  data-explorer/kusto/query/scalar-data-types/dynamic.md
Labels: do-not-merge

#157 Fix git push error for protected CLA branch
  data-explorer/ingest-data-streaming.md
  data-explorer/kusto/concepts/runawayqueries.md
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/management/data-export/export-data-to-an-external-table.md
  data-explorer/kusto/management/data-ingestion/clear-schema-cache-command.md
  data-explorer/kusto/management/data-ingestion/eventgrid.md
  data-explorer/kusto/management/data-ingestion/streaming-ingestion-schema-changes.md
  data-explorer/kusto/management/databasecursor.md
  data-explorer/kusto/management/drop-ingestion-mapping-command.md
  data-explorer/kusto/management/execute-database-script.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/kusto/management/partitioning-policy.md
  data-explorer/kusto/management/retentionpolicy.md
  data-explorer/kusto/management/row-level-security-policy.md
  data-explorer/kusto/query/bag-merge-function.md
  data-explorer/kusto/query/extractallfunction.md
  data-explorer/kusto/query/indexofregexfunction.md
  data-explorer/kusto/query/inoperator.md
  data-explorer/kusto/query/packallfunction.md
  data-explorer/kusto/query/parsecsvfunction.md
  data-explorer/kusto/query/schema-entities/externaltables.md
  data-explorer/kusto/query/schemamergeplugin.md
  data-explorer/machine-learning-clustering.md
  data-explorer/toc.yml
  data-explorer/web-query-data.md
Labels: do-not-merge

#158 Fix git push error for protected CLA branch
  data-explorer/kusto/query/pivotplugin.md
Labels: do-not-merge

#159 Fix git push error for protected CLA branch
  data-explorer/kusto/management/mergepolicy.md
  data-explorer/kusto/management/show-databases.md
  data-explorer/kusto/query/bag-unpackplugin.md
  data-explorer/kusto/query/base64_decode_tostringfunction.md
  data-explorer/kusto/query/makestringfunction.md
  data-explorer/kusto/query/percentrank-tdigestfunction.md
  data-explorer/kusto/query/schema-entities/tables.md
Labels: do-not-merge

#160 Update links to Kusto Data Explorer to plain URLs
  data-explorer/kusto/tools/kusto-webexplorer.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#161 Fix git push error for protected CLA branch
  data-explorer/kusto/query/mvexpandoperator.md
Labels: do-not-merge

#163 Fix git push error for protected CLA branch
  data-explorer/data-lake-query-data.md
  data-explorer/kusto/concepts/errorsinnativecode.md
  data-explorer/kusto/management/clear-query-results-cache-command.md
  data-explorer/kusto/management/query-results-cache-commands.md
  data-explorer/kusto/management/show-query-results-cache-command.md
  data-explorer/kusto/query/externaldata-operator.md
  data-explorer/kusto/query/query-results-cache.md
  data-explorer/toc.yml
Labels: do-not-merge

#164 "Format" in wrong place in queue payload
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#168 Fix git push error for protected CLA branch
  data-explorer/kusto/query/parseoperator.md
  data-explorer/kusto/query/parsewhereoperator.md
  data-explorer/kusto/query/searchoperator.md
Labels: do-not-merge

#171 Fix git push error for protected CLA branch
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/query/best-practices.md
  data-explorer/kusto/query/binoperators.md
  data-explorer/kusto/query/broadcastjoin.md
  data-explorer/kusto/query/evaluateoperator.md
  data-explorer/kusto/query/functions/index.md
  data-explorer/kusto/query/join-timewindow.md
  data-explorer/kusto/query/joincrosscluster.md
  data-explorer/kusto/query/notbetweenoperator.md
  data-explorer/kusto/query/patternstatement.md
  data-explorer/kusto/query/percentiles-aggfunction.md
  data-explorer/kusto/query/prevfunction.md
  data-explorer/kusto/query/projectoperator.md
  data-explorer/kusto/query/queries.md
  data-explorer/kusto/query/query-results-cache.md
  data-explorer/kusto/query/rolling-percentile-plugin.md
  data-explorer/kusto/query/scalar-data-types/index.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/schema-entities/index.md
  data-explorer/kusto/query/statements.md
  data-explorer/kusto/query/todoublefunction.md
  data-explorer/kusto/query/totimespanfunction.md
  data-explorer/kusto/query/usinghlltdigest.md
  data-explorer/kusto/query/windowsfunctions.md
  data-explorer/toc.yml
Labels: do-not-merge

#169 Fix typo
  data-explorer/kusto/query/restrictstatement.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#172 Fix git push error for protected CLA branch
  data-explorer/kusto/query/bag-unpackplugin.md
  data-explorer/kusto/query/count-aggfunction.md
  data-explorer/kusto/query/sqlcheatsheet.md
  data-explorer/kusto/query/toscalarfunction.md
Labels: do-not-merge

#174 Fix git push error for protected CLA branch
  data-explorer/kusto/management/create-alter-function.md
  data-explorer/kusto/query/basketplugin.md
Labels: do-not-merge

#175 Fix git push error for protected CLA branch
  data-explorer/includes/data-explorer-one-click-column-table.md
  data-explorer/includes/data-explorer-one-click-command-editor.md
  data-explorer/includes/data-explorer-one-click-ingestion-query-data.md
  data-explorer/includes/media/data-explorer-one-click-command-editor/edit-view.png
  data-explorer/ingest-data-one-click.md
  data-explorer/kusto/concepts/fact-and-dimension-tables.md
  data-explorer/kusto/concepts/index.md
  data-explorer/kusto/management/data-ingestion/ingest-from-query.md
  data-explorer/kusto/management/drop-table-command.md
  data-explorer/kusto/management/rowlevelsecuritypolicy.md
  data-explorer/kusto/query/bag-merge-function.md
  data-explorer/kusto/query/bagkeysfunction.md
  data-explorer/kusto/query/datatableoperator.md
  data-explorer/kusto/query/datatypes-string-operators.md
  data-explorer/kusto/query/dcount-aggfunction.md
  data-explorer/kusto/query/externaldata-operator.md
  data-explorer/kusto/query/indexoffunction.md
  data-explorer/kusto/query/parsejsonfunction.md
  data-explorer/kusto/query/parseoperator.md
  data-explorer/kusto/query/reversefunction.md
  data-explorer/kusto/query/scalar-data-types/string.md
  data-explorer/kusto/query/series-decompose-anomaliesfunction.md
  data-explorer/kusto/query/series-iirfunction.md
  data-explorer/kusto/query/setintersectfunction.md
  data-explorer/kusto/query/setunionfunction.md
  data-explorer/kusto/query/strcat-delimfunction.md
  data-explorer/kusto/query/tdigest-aggfunction.md
  data-explorer/kusto/query/todatetimefunction.md
  data-explorer/kusto/tools/kusto-explorer-shortcuts.md
  data-explorer/media/ingest-data-one-click/welcome-ingestion.png
  data-explorer/media/one-click-ingestion-existing-table/edit-view.png
  data-explorer/media/one-click-ingestion-existing-table/from-file.png
  data-explorer/media/one-click-ingestion-existing-table/json-levels.png
  data-explorer/media/one-click-ingestion-existing-table/one-click-data-ingestion-complete.png
  data-explorer/media/one-click-ingestion-existing-table/start-ingestion.png
  data-explorer/media/one-click-ingestion-new-table/continuous-button.png
  data-explorer/media/one-click-ingestion-new-table/event-hub-create.png
  data-explorer/one-click-ingestion-existing-table.md
  data-explorer/one-click-ingestion-new-table.md
  data-explorer/toc.yml
Labels: do-not-merge

#176 Fix git push error for protected CLA branch
  data-explorer/kusto/management/data-ingestion/eventhub.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/inferstorageschemaplugin.md
  data-explorer/kusto/query/scalar-data-types/dynamic.md
Labels: do-not-merge

#178 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/query-results-cache.md
Labels: do-not-merge

#180 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#181 Update takeoperator.md
  data-explorer/kusto/query/takeoperator.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#184 Fix git push error for protected CLA branch
  data-explorer/kusto/query/parse-command-line.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/schema-entities/entity-references.md
  data-explorer/kusto/query/sha256hashfunction.md
  data-explorer/kusto/tools/kusto-explorer-troubleshooting.md
  data-explorer/toc.yml
  data-explorer/vnet-create-cluster-portal.md
Labels: do-not-merge

#173 Refactor make-series to use new from-to-step syntax
  data-explorer/kusto/query/series-fill-backwardfunction.md
  data-explorer/kusto/query/series-fill-constfunction.md
  data-explorer/kusto/query/series-fill-forwardfunction.md
  data-explorer/kusto/query/series-fill-linearfunction.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, do-not-merge

#187 Fix git push error for protected CLA branch
  data-explorer/kusto/management/access-control/index.md
  data-explorer/kusto/management/alter-docstring-function.md
  data-explorer/kusto/management/data-export/index.md
  data-explorer/kusto/query/findoperator.md
  data-explorer/kusto/query/join-timewindow.md
  data-explorer/kusto/query/make-bag-if-aggfunction.md
  data-explorer/kusto/query/queryparametersstatement.md
  data-explorer/kusto/query/series-periods-detectfunction.md
  data-explorer/kusto/query/sha256hashfunction.md
  data-explorer/kusto/query/toboolfunction.md
  data-explorer/kusto/query/welch-testfunction.md
  data-explorer/toc.yml
Labels: do-not-merge

#191 Minor typo (THe => The)
  data-explorer/kusto/query/queryparametersstatement.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#193 Adds Azure Data Explorer Training
  data-explorer/index.yml
Labels: aq-pr-triaged, data-explorer/svc, do-not-merge, review-team-triage

#194 Fix git push error for protected CLA branch
  data-explorer/kusto/api/python/kusto-python-client-library.md
  data-explorer/kusto/management/access-control/index.md
  data-explorer/kusto/query/hashfunction.md
  data-explorer/kusto/query/make-bag-aggfunction.md
  data-explorer/kusto/query/md5hashfunction.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/setintersectfunction.md
  data-explorer/toc.yml
Labels: do-not-merge
