Repository MicrosoftDocs/dataexplorer-docs, pull requests merged in 2020-07, with the labels that each got.

#196 Fix git push error for protected CLA branch
  data-explorer/kusto/management/streamingingestion-policy.md
  data-explorer/kusto/query/mvexpandoperator.md
  data-explorer/toc.yml
Labels: do-not-merge

#197 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
  data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md
  data-explorer/kusto/concepts/errorsinnativecode.md
  data-explorer/kusto/concepts/querylimits.md
  data-explorer/kusto/management/data-ingestion/ingest-from-storage.md
Labels: do-not-merge

#198 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
  data-explorer/kusto/concepts/querylimits.md
  data-explorer/kusto/management/restrictedviewaccesspolicy.md
  data-explorer/kusto/query/buildschema-aggfunction.md
  data-explorer/kusto/query/parse-versionfunction.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/query/renderoperator.md
  data-explorer/kusto/query/rplugin.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/sliding-window-counts-plugin.md
  data-explorer/kusto/query/sqlrequestplugin.md
  data-explorer/kusto/tools/synckusto.md
Labels: do-not-merge

#201 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/devops.md
  data-explorer/kusto/management/alter-merge-table-column.md
  data-explorer/kusto/management/best-practices.md
  data-explorer/kusto/management/cache-policy.md
  data-explorer/kusto/management/capacity-policy.md
  data-explorer/kusto/management/create-merge-table-command.md
  data-explorer/kusto/management/create-table-command.md
  data-explorer/kusto/management/create-tables-command.md
  data-explorer/kusto/management/drop-column.md
  data-explorer/kusto/management/index.md
  data-explorer/kusto/management/ingestiontime-policy.md
  data-explorer/kusto/management/merge-policy.md
  data-explorer/kusto/management/mergepolicy.md
  data-explorer/kusto/management/partitioning-policy.md
  data-explorer/kusto/management/rename-column.md
  data-explorer/kusto/management/restrictedviewaccess-policy.md
  data-explorer/kusto/management/restrictedviewaccesspolicy.md
  data-explorer/kusto/management/retention-policy.md
  data-explorer/kusto/management/row-level-security-policy.md
  data-explorer/kusto/management/roworder-policy.md
  data-explorer/kusto/management/sandbox-policy.md
  data-explorer/kusto/management/schema.md
  data-explorer/kusto/management/sharding-policy.md
  data-explorer/kusto/management/shardingpolicy.md
  data-explorer/kusto/management/show-function.md
  data-explorer/kusto/management/show-ingestion-mapping-command.md
  data-explorer/kusto/management/streamingingestion-policy.md
  data-explorer/kusto/management/tables.md
  data-explorer/kusto/management/update-policy.md
  data-explorer/kusto/query/re2.md
  data-explorer/kusto/query/sqlcheatsheet.md
  data-explorer/kusto/query/useranalytics.md
  data-explorer/toc.yml
Labels: do-not-merge

#200 Broken link fixed week29
  data-explorer/kusto/tools/kusto-explorer-using.md
  data-explorer/kusto/tools/kusto-explorer.md
Labels: Change sent to author, data-explorer/svc, ready-to-merge

#202 Fix git push error for protected CLA branch
  data-explorer/data-connection-event-grid-csharp.md
  data-explorer/data-connection-event-grid-python.md
  data-explorer/data-connection-event-grid-resource-manager.md
  data-explorer/ingest-data-event-grid.md
  data-explorer/kusto/concepts/errorsinnativecode.md
  data-explorer/kusto/management/best-practices.md
  data-explorer/kusto/management/data-ingestion/eventgrid.md
  data-explorer/kusto/management/images/eventgrid/create-event-grid-subscription-1.png
  data-explorer/kusto/management/images/eventgrid/create-event-grid-subscription-2.png
  data-explorer/kusto/management/images/eventgrid/filters-tab.png
  data-explorer/kusto/query/tointfunction.md
  data-explorer/media/ingest-data-event-grid/clean-up-resources-find-eventhub-namespace-delete.png
  data-explorer/media/ingest-data-event-grid/clean-up-resources-select-all-resource.png
  data-explorer/media/ingest-data-event-grid/clean-up-resources-select-data-ingestion.png
  data-explorer/media/ingest-data-event-grid/clean-up-resources-select-database.png
  data-explorer/media/ingest-data-event-grid/clean-up-resources-select-events.png
  data-explorer/media/ingest-data-event-grid/create-event-grid-data-connection-basics.png
  data-explorer/media/ingest-data-event-grid/create-event-grid-data-connection-ingest-properties.png
  data-explorer/media/ingest-data-event-grid/create-event-grid-data-connection-review-create.png
  data-explorer/media/ingest-data-event-grid/create-event-grid-data-connection.png
  data-explorer/media/ingest-data-event-grid/create-event-grid-subscription.png
  data-explorer/media/ingest-data-event-grid/data-ingestion-create.png
  data-explorer/media/ingest-data-event-grid/delete-event-grid-subscription.png
  data-explorer/media/ingest-data-event-grid/delete-namespace.png
  data-explorer/media/ingest-data-event-grid/delete-resources-select.png
  data-explorer/media/ingest-data-event-grid/deploy-event-grid-resources.png
  data-explorer/media/ingest-data-event-grid/filter-settings.png
  data-explorer/media/ingest-data-event-grid/run-create-table.png
  data-explorer/media/ingest-data-event-grid/select-test-database.png
Labels: do-not-merge

#203 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/includes/data-explorer-one-click-ingestion-query-data.md
  data-explorer/ingest-data-one-click.md
  data-explorer/kusto/api/connection-strings/index.md
  data-explorer/kusto/management/alter-extent.md
  data-explorer/kusto/management/drop-extent-tags.md
  data-explorer/kusto/management/drop-extents.md
  data-explorer/kusto/management/extents-commands.md
  data-explorer/kusto/management/merge-extents.md
  data-explorer/kusto/management/move-extents.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/management/replace-extents.md
  data-explorer/kusto/management/show-extents.md
  data-explorer/kusto/query/joinoperator.md
  data-explorer/media/one-click-ingestion-new-table/continuous-button.png
  data-explorer/one-click-ingestion-existing-table.md
  data-explorer/one-click-ingestion-new-table.md
  data-explorer/toc.yml
Labels: do-not-merge

#206 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/vnet-deploy-troubleshoot.md
Labels: do-not-merge

#208 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/ingest-data-overview.md
  data-explorer/kusto/concepts/index.md
  data-explorer/kusto/index.md
  data-explorer/kusto/tools/index.md
  data-explorer/kusto/tools/synckusto.md
  data-explorer/toc.yml
  data-explorer/tools-integrations-overview.md
Labels: do-not-merge

#209 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/ingest-data-one-click.md
  data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md
  data-explorer/kusto/api/powershell/powershell.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/scalar-data-types/dynamic.md
  data-explorer/kusto/query/tutorial.md
  data-explorer/net-sdk-ingest-data.md
  data-explorer/toc.yml
  data-explorer/tools-integrations-overview.md
  data-explorer/vnet-deploy-troubleshoot.md
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#210 Fix git push error for protected CLA branch
  data-explorer/manage-cluster-security.md
Labels: do-not-merge

#205 Update ingest-data-streaming.md
  data-explorer/ingest-data-streaming.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, do-not-merge

#213 Fix git push error for protected CLA branch
  data-explorer/kusto/query/best-practices.md
  data-explorer/kusto/query/geo-distance-point-to-line-function.md
  data-explorer/kusto/query/geo-line-densify-function.md
  data-explorer/kusto/query/geo-point-in-polygon-function.md
  data-explorer/kusto/query/geo-polygon-densify-function.md
  data-explorer/kusto/query/geo-polygon-to-s2cells-function.md
  data-explorer/kusto/query/materializefunction.md
  data-explorer/kusto/query/scalar-data-types/dynamic.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/tools/kusto-explorer-using.md
  data-explorer/kusto/tools/kusto-explorer.md
  data-explorer/net-sdk-ingest-data.md
  data-explorer/toc.yml
Labels: do-not-merge

#214 Fix git push error for protected CLA branch
  data-explorer/kusto/query/extentidfunction.md
  data-explorer/kusto/query/ingestiontimefunction.md
  data-explorer/kusto/query/letstatement.md
  data-explorer/query-monitor-data.md
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#216 Fix git push error for protected CLA branch
  data-explorer/query-monitor-data.md
Labels: do-not-merge

#217 Fix git push error for protected CLA branch
  data-explorer/tools-integrations-overview.md
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#220 Fix git push error for protected CLA branch
  data-explorer/includes/ingest-data-streaming-disable.md
  data-explorer/includes/ingest-data-streaming-intro.md
  data-explorer/includes/ingest-data-streaming-limitations.md
  data-explorer/includes/ingest-data-streaming-types.md
  data-explorer/ingest-data-streaming-csharp.md
  data-explorer/ingest-data-streaming.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/media/adx-proxy/function-query-adx-proxy.png
  data-explorer/media/ingest-data-streaming/cluster-creation-enable-streaming.png
  data-explorer/media/ingest-data-streaming/cluster-select-query-tab.png
  data-explorer/media/ingest-data-streaming/create-table.png
  data-explorer/media/ingest-data-streaming/database-streaming-ingestion-policy-enable.png
  data-explorer/media/ingest-data-streaming/define-streaming-ingestion-policy.png
  data-explorer/media/ingest-data-streaming/delete-streaming-ingestion-policy.png
  data-explorer/media/ingest-data-streaming/streaming-ingestion-off.png
  data-explorer/media/ingest-data-streaming/streaming-ingestion-on.png
  data-explorer/net-sdk-ingest-data.md
  data-explorer/query-monitor-data.md
  data-explorer/toc.yml
Labels: do-not-merge

#221 Fix git push error for protected CLA branch
  data-explorer/kusto/management/capacitypolicy.md
Labels: do-not-merge

#222 Fix git push error for protected CLA branch
  data-explorer/kusto/management/batching-policy.md
Labels: do-not-merge

#219 remove suspend limitation from follower
  data-explorer/follower.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, ready-to-merge

#223 Fix git push error for protected CLA branch
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/tools/kusto-explorer-troubleshooting.md
Labels: do-not-merge

#224 Fix git push error for protected CLA branch
  data-explorer/kusto/management/cachepolicy.md
  data-explorer/kusto/management/rowlevelsecuritypolicy.md
Labels: do-not-merge

#225 Fix git push error for protected CLA branch
  data-explorer/kusto/management/clear-query-results-cache-command.md
  data-explorer/kusto/management/show-query-results-cache-command.md
Labels: do-not-merge

#227 Fix git push error for protected CLA branch
  data-explorer/kusto/tools/kusto-explorer-troubleshooting.md
  data-explorer/kusto/tools/kusto-explorer-using.md
  data-explorer/kusto/tools/kusto-explorer.md
  data-explorer/query-monitor-data.md
  data-explorer/web-query-data.md
Labels: do-not-merge

#228 Add examples to make_list
  data-explorer/kusto/query/makelist-aggfunction.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#229 Fix git push error for protected CLA branch
  data-explorer/data-explorer-overview.md
  data-explorer/kusto/concepts/data-purge.md
  data-explorer/kusto/management/data-ingestion/eventgrid.md
Labels: do-not-merge

#231 Fix git push error for protected CLA branch
  data-explorer/kusto/concepts/data-purge.md
  data-explorer/kusto/management/data-export/continuous-data-export.md
  data-explorer/kusto/management/data-export/export-data-to-storage.md
  data-explorer/kusto/management/data-ingestion/eventgrid.md
  data-explorer/kusto/management/rowlevelsecuritypolicy.md
Labels: do-not-merge

#235 Update best-practices.md
  data-explorer/kusto/query/best-practices.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#236 Update best-practices.md
  data-explorer/kusto/query/best-practices.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#237 Fix git push error for protected CLA branch
  data-explorer/kusto/query/best-practices.md
  data-explorer/kusto/query/materializefunction.md
  data-explorer/kusto/query/orderoperator.md
  data-explorer/lightingest.md
  data-explorer/media/lightingest/lightingest-download-area.png
Labels: do-not-merge

#243 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/kusto-ingest-client-errors.md
Labels: do-not-merge

#244 Broken link fixed.
  data-explorer/redash.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#247 Fix git push error for protected CLA branch
  data-explorer/kusto/tools/kusto-explorer-using.md
  data-explorer/spark-connector.md
Labels: do-not-merge

#251 Fix git push error for protected CLA branch
  data-explorer/kusto/query/scalar-data-types/null-values.md
Labels: do-not-merge
