Repository MicrosoftDocs/dataexplorer-docs, pull requests merged in 2020-04, with the labels that each got.

#11 Fix git push error for protected CLA branch
  data-explorer/ingestion-supported-formats.md
  data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md
  data-explorer/kusto/query/letstatement.md
  data-explorer/language-extensions.md
Labels: do-not-merge

#10 Adding two Key Vault & identity endpoints for enabling Encryption option
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#5 Missing syntax highlighting
  data-explorer/kusto/query/functions/user-defined-functions.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#2 Change "supplant" to "supplement"
  data-explorer/kusto/concepts/index.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#1 Fix syntax for .show databases
  data-explorer/kusto/management/show-databases.md
Labels: Change sent to author, data-explorer/svc, ready-to-merge

#9 Update countoperator.md
  data-explorer/kusto/query/countoperator.md
Labels: do-not-merge

#6 Adding Go + removing redundancies
  data-explorer/kusto/api/client-libraries.md
  data-explorer/kusto/api/golang/kusto-golang-client-library.md
  data-explorer/kusto/api/index.md
  data-explorer/kusto/toc.yml
Labels: ready-to-merge, review-team-triage

#12 Fix git push error for protected CLA branch
  data-explorer/using-diagnostic-logs.md
Labels: do-not-merge

#19 Fix git push error for protected CLA branch
  data-explorer/ingest-json-formats.md
  data-explorer/kusto/api/golang/kusto-golang-client-library.md
  data-explorer/kusto/query/activity-engagement-plugin.md
  data-explorer/kusto/query/activity-metrics-plugin.md
  data-explorer/kusto/query/any-aggfunction.md
  data-explorer/kusto/query/anyif-aggfunction.md
  data-explorer/kusto/query/arg-min-aggfunction.md
  data-explorer/kusto/query/arrayifffunction.md
  data-explorer/kusto/query/autoclusterplugin.md
  data-explorer/kusto/query/basketplugin.md
  data-explorer/kusto/query/best-practices.md
  data-explorer/kusto/query/current-principal-ismemberoffunction.md
  data-explorer/kusto/query/dcount-aggfunction.md
  data-explorer/kusto/query/findoperator.md
  data-explorer/kusto/query/geo-distance-2points-function.md
  data-explorer/kusto/query/geo-distance-point-to-line-function.md
  data-explorer/kusto/query/geo-point-in-circle-function.md
  data-explorer/kusto/query/geo-point-in-polygon-function.md
  data-explorer/kusto/query/geo-point-to-s2cell-function.md
  data-explorer/kusto/query/make-seriesoperator.md
  data-explorer/kusto/query/parse-xmlfunction.md
  data-explorer/kusto/query/parsecsvfunction.md
  data-explorer/kusto/query/percentiles-aggfunction.md
  data-explorer/kusto/query/sampledistinctoperator.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/schema-entities/clusters.md
  data-explorer/kusto/query/schema-entities/index.md
  data-explorer/kusto/query/series-decompose-anomaliesfunction.md
  data-explorer/kusto/query/series-decompose-forecastfunction.md
  data-explorer/kusto/query/series-decomposefunction.md
  data-explorer/kusto/query/series-firfunction.md
  data-explorer/kusto/query/series-fit-2lines-dynamicfunction.md
  data-explorer/kusto/query/series-fit-2linesfunction.md
  data-explorer/kusto/query/series-fit-line-dynamicfunction.md
  data-explorer/kusto/query/series-fit-linefunction.md
  data-explorer/kusto/query/series-outliersfunction.md
  data-explorer/kusto/query/series-periods-detectfunction.md
  data-explorer/kusto/query/series-periods-validatefunction.md
  data-explorer/kusto/query/series-seasonalfunction.md
  data-explorer/kusto/query/session-count-plugin.md
  data-explorer/kusto/query/shufflequery.md
  data-explorer/kusto/query/stdev-aggfunction.md
  data-explorer/kusto/query/stdevp-aggfunction.md
  data-explorer/kusto/query/summarizeoperator.md
  data-explorer/kusto/query/tophittersoperator.md
  data-explorer/kusto/query/tutorial.md
  data-explorer/kusto/query/usinghlltdigest.md
Labels: do-not-merge

#21 Fix git push error for protected CLA branch
  data-explorer/kusto/management/merge-policy.md
  data-explorer/kusto/management/partitioning-policy.md
Labels: do-not-merge

#22 Fix typo (cluser -> cluster)
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#24 Revert "Adding two Key Vault & identity endpoints for enabling Encryption option"
  data-explorer/vnet-deployment.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#25 Fix git push error for protected CLA branch
  data-explorer/docfx.json
  data-explorer/kusto/management/batching-policy.md
  data-explorer/kusto/management/cache-policy.md
  data-explorer/kusto/management/calloutpolicy.md
  data-explorer/kusto/management/commands.md
  data-explorer/kusto/management/create-alter-function.md
  data-explorer/kusto/management/create-function.md
  data-explorer/kusto/management/create-ingestion-mapping-command.md
  data-explorer/kusto/management/create-merge-tables-command.md
  data-explorer/kusto/management/create-table-command.md
  data-explorer/kusto/management/create-tables-command.md
  data-explorer/kusto/management/drop-function.md
  data-explorer/kusto/management/drop-ingestion-mapping-command.md
  data-explorer/kusto/management/drop-table-command.md
  data-explorer/kusto/management/extents-commands.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/query/parse-xmlfunction.md
  data-explorer/kusto/query/parsejsonfunction.md
  data-explorer/kusto/query/parsepathfunction.md
  data-explorer/kusto/query/parseurlqueryfunction.md
  data-explorer/kusto/query/prevfunction.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/query/rangefunction.md
  data-explorer/kusto/query/renderoperator.md
  data-explorer/kusto/query/rplugin.md
Labels: do-not-merge

#26 Fix git push error for protected CLA branch
  data-explorer/kusto/query/aliasstatement.md
  data-explorer/kusto/query/clusterfunction.md
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/current-principal-ismemberoffunction.md
  data-explorer/kusto/query/current-principalfunction.md
  data-explorer/kusto/query/cursorafterfunction.md
  data-explorer/kusto/query/cursorbeforeoratfunction.md
  data-explorer/kusto/query/cursorcurrent.md
  data-explorer/kusto/query/databasefunction.md
  data-explorer/kusto/query/datatableoperator.md
  data-explorer/kusto/query/extentidfunction.md
  data-explorer/kusto/query/extenttagsfunction.md
  data-explorer/kusto/query/findoperator.md
  data-explorer/kusto/query/ingestiontimefunction.md
  data-explorer/kusto/query/joincrosscluster.md
  data-explorer/kusto/query/joinoperator.md
  data-explorer/kusto/query/patternstatement.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/query/queryparametersstatement.md
  data-explorer/kusto/query/renderoperator.md
  data-explorer/kusto/query/restrictstatement.md
  data-explorer/kusto/query/rplugin.md
  data-explorer/kusto/query/scalar-data-types/null-values.md
  data-explorer/kusto/query/setstatement.md
  data-explorer/kusto/query/sqlrequestplugin.md
  data-explorer/kusto/query/statements.md
  data-explorer/kusto/query/tablefunction.md
  data-explorer/kusto/query/tutorial.md
  data-explorer/kusto/query/unionoperator.md
  data-explorer/kusto/query/usinghlltdigest.md
  data-explorer/kusto/toc.yml
Labels: do-not-merge

#27 Fix git push error for protected CLA branch
  data-explorer/ingestion-supported-formats.md
  data-explorer/kusto/api/r/kusto-r-client-library.md
  data-explorer/kusto/concepts/data-purge.md
  data-explorer/kusto/query/activity-engagement-plugin.md
  data-explorer/kusto/query/activity-metrics-plugin.md
  data-explorer/kusto/query/any-aggfunction.md
  data-explorer/kusto/query/anyif-aggfunction.md
  data-explorer/kusto/query/arg-min-aggfunction.md
  data-explorer/kusto/query/dcount-aggfunction.md
  data-explorer/kusto/query/distinctoperator.md
  data-explorer/kusto/query/geo-distance-2points-function.md
  data-explorer/kusto/query/geo-point-to-geohash-function.md
  data-explorer/kusto/query/images/activity-engagement-plugin/activity-engagement-dau-mau-mod3.png
  data-explorer/kusto/query/images/activity-engagement-plugin/activity-engagement-dau-mau.png
  data-explorer/kusto/query/images/activity-engagement-plugin/activity-engagement-dau-wau.png
  data-explorer/kusto/query/images/activity-metrics-plugin/activity-metrics-churn-and-retention.png
  data-explorer/kusto/query/images/activity-metrics-plugin/activity-metrics-dcount-and-dcount-newvalues.png
  data-explorer/kusto/query/images/aggfunction/any1.png
  data-explorer/kusto/query/images/aggfunction/any2.png
  data-explorer/kusto/query/images/aggfunction/any3.png
  data-explorer/kusto/query/images/arg-min-aggfunction/arg-min.png
  data-explorer/kusto/query/images/dcount-aggfunction/dcount.png
  data-explorer/kusto/query/images/dcount-aggfunction/hll-error-distribution.png
  data-explorer/kusto/query/images/distinctoperator/distinct.PNG
  data-explorer/kusto/query/images/geo-distance-2points-function/distance_2points_seattle_los_angeles.png
  data-explorer/kusto/query/images/geo-distance-2points-function/line_seattle_london.png
  data-explorer/kusto/query/images/geo-point-to-geohash-function/geohash.png
Labels: do-not-merge

#28 Fix git push error for protected CLA branch
  data-explorer/flow.md
  data-explorer/includes/data-explorer-one-click-ingestion-types.md
  data-explorer/includes/iot-hub-include-create-hub.md
  data-explorer/ingest-data-no-code.md
  data-explorer/k2bridge.md
  data-explorer/kusto/api/client-libraries.md
  data-explorer/kusto/api/connection-strings/kusto.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
  data-explorer/kusto/management/alter-table-docstring-command.md
  data-explorer/kusto/management/cluster-follower.md
  data-explorer/kusto/management/create-table-command.md
  data-explorer/kusto/management/data-export/continuous-data-export.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/tools/kusto-explorer-options.md
  data-explorer/kusto/tools/kusto-explorer.md
  data-explorer/spark-connector.md
Labels: do-not-merge

#29 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/shufflequery.md
Labels: do-not-merge

#31 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#35 spelling mistake
  data-explorer/kusto/management/data-ingestion/eventhub.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#34 Spelling mistake
  data-explorer/kusto/management/data-ingestion/eventhub.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#33 Proofread
  data-explorer/kusto/api/rest/authentication.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#41 Fix git push error for protected CLA branch
  data-explorer/kusto/management/batching-policy.md
  data-explorer/kusto/management/batchingpolicy.md
  data-explorer/kusto/management/create-ingestion-mapping-command.md
  data-explorer/kusto/management/ingestiontime-policy.md
  data-explorer/kusto/management/restrictedviewaccess-policy.md
  data-explorer/kusto/management/restrictedviewaccesspolicy.md
  data-explorer/kusto/management/retention-policy.md
  data-explorer/kusto/management/retentionpolicy.md
  data-explorer/kusto/management/update-policy.md
  data-explorer/kusto/management/updatepolicy.md
  data-explorer/vnet-create-cluster-portal.md
Labels: do-not-merge

#46 Update ingest-data-one-click.md
  data-explorer/ingest-data-one-click.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#47 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioning-policy.md
Labels: do-not-merge

#49 Update manage-cluster-horizontal-scaling.md
  data-explorer/manage-cluster-horizontal-scaling.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#36 multiple rewrites and fixes
  data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, do-not-merge

#50 Fix git push error for protected CLA branch
  data-explorer/kusto/api/rest/response2.md
Labels: do-not-merge

#51 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/extractallfunction.md
Labels: do-not-merge
