Repository MicrosoftDocs/dataexplorer-docs, pull requests merged in 2020-05, with the labels that each got.

#55 Fix git push error for protected CLA branch
  data-explorer/kusto/query/arrayindexoffunction.md
  data-explorer/kusto/query/arrayslicefunction.md
  data-explorer/kusto/query/arraysplitfunction.md
  data-explorer/kusto/query/clusterfunction.md
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/current-principal-ismemberoffunction.md
  data-explorer/kusto/query/current-principalfunction.md
  data-explorer/kusto/query/cursorafterfunction.md
  data-explorer/kusto/query/cursorbeforeoratfunction.md
  data-explorer/kusto/query/cursorcurrent.md
  data-explorer/kusto/query/databasefunction.md
  data-explorer/kusto/query/extentidfunction.md
  data-explorer/kusto/query/extenttagsfunction.md
  data-explorer/kusto/query/joincrosscluster.md
  data-explorer/kusto/query/materializefunction.md
  data-explorer/kusto/query/patternstatement.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/query/queryparametersstatement.md
  data-explorer/kusto/query/restrictstatement.md
  data-explorer/kusto/query/rplugin.md
  data-explorer/kusto/query/series-fill-linearfunction.md
  data-explorer/kusto/query/setstatement.md
  data-explorer/kusto/query/sqlrequestplugin.md
  data-explorer/kusto/query/statements.md
  data-explorer/kusto/query/tdigest-mergefunction.md
  data-explorer/kusto/query/tutorial.md
Labels: do-not-merge

#56 Fix git push error for protected CLA branch
  data-explorer/ingest-data-event-grid.md
  data-explorer/kusto/concepts/sandboxes.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/query/activity-counts-metrics-plugin.md
  data-explorer/kusto/query/aliasstatement.md
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/diffpatternsplugin.md
  data-explorer/kusto/query/hll-aggfunction.md
  data-explorer/kusto/query/hllmergefunction.md
  data-explorer/kusto/query/rank-tdigest.md
  data-explorer/kusto/query/series-fill-backwardfunction.md
  data-explorer/kusto/query/series-fill-constfunction.md
  data-explorer/kusto/query/series-fill-forwardfunction.md
  data-explorer/kusto/query/shufflequery.md
  data-explorer/kusto/query/tostringfunction.md
  data-explorer/kusto/query/useranalytics.md
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#53 Update create-clusert-database-cli.md
  data-explorer/create-cluster-database-cli.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, do-not-merge

#59 Fix git push error for protected CLA branch
  data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md
  data-explorer/kusto/api/netfx/about-kusto-ingest.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-permissions.md
  data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md
  data-explorer/kusto/api/rest/response.md
  data-explorer/kusto/api/tds/clients.md
  data-explorer/kusto/api/tds/linkedserver.md
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#60 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/about-kusto-ingest.md
  data-explorer/kusto/api/netfx/controlling-tracing.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
  data-explorer/kusto/api/rest/streaming-ingest.md
  data-explorer/kusto/api/tds/aad.md
  data-explorer/kusto/api/tds/clients.md
  data-explorer/kusto/management/access-control/aad.md
  data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md
  data-explorer/kusto/management/access-control/index.md
  data-explorer/kusto/management/data-ingestion/eventhub.md
  data-explorer/sisense.md
  data-explorer/vnet-deployment.md
Labels: do-not-merge

#62 Fix git push error for protected CLA branch
  data-explorer/docfx.json
  data-explorer/flow-usage.md
  data-explorer/flow.md
  data-explorer/kusto/management/updatepolicy.md
Labels: do-not-merge

#65 Fix git push error for protected CLA branch
  data-explorer/kusto/api/rest/streaming-ingest.md
  data-explorer/kusto/concepts/data-purge.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/active-users-count-plugin.md
  data-explorer/kusto/query/row-window-session-function.md
  data-explorer/kusto/query/series-decomposefunction.md
Labels: do-not-merge

#67 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/kusto/management/databases.md
  data-explorer/kusto/management/drop-database.md
  data-explorer/kusto/toc.yml
Labels: do-not-merge

#68 Fix git push error for protected CLA branch
  data-explorer/kusto/management/extents-overview.md
  data-explorer/kusto/query/datatypes-string-operators.md
Labels: do-not-merge

#69 Fix git push error for protected CLA branch
  data-explorer/kusto/management/data-export/export-data-to-an-external-table.md
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#71 Fix git push error for protected CLA branch
  data-explorer/kusto/api/client-libraries.md
  data-explorer/kusto/api/images/direct-ingest.png
  data-explorer/kusto/api/images/queued-ingest.png
  data-explorer/kusto/api/images/web-ux.png
  data-explorer/kusto/api/netfx/controlling-tracing.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-permissions.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-reference.md
  data-explorer/kusto/api/powershell/powershell.md
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/management/data-export/continuous-data-export.md
  data-explorer/kusto/management/data-export/export-data-to-an-external-table.md
  data-explorer/kusto/management/external-sql-tables.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/array_shift_leftfunction.md
  data-explorer/kusto/query/dcount-intersect-plugin.md
  data-explorer/kusto/query/funnel-sequence-completion-plugin.md
  data-explorer/kusto/query/funnel-sequence-plugin.md
  data-explorer/kusto/query/inferstorageschemaplugin.md
  data-explorer/kusto/query/make-list-with-nulls-aggfunction.md
  data-explorer/kusto/query/makelist-aggfunction.md
  data-explorer/kusto/query/mv-applyoperator.md
  data-explorer/kusto/query/parsewhereoperator.md
  data-explorer/kusto/query/percentile-tdigestfunction.md
  data-explorer/kusto/query/series-fit-2lines-dynamicfunction.md
  data-explorer/kusto/query/sliding-window-counts-plugin.md
  data-explorer/kusto/query/tdigest-aggfunction.md
  data-explorer/kusto/query/usinghlltdigest.md
  data-explorer/kusto/toc.yml
Labels: do-not-merge

#75 storage.md: Fixed formatting
  data-explorer/kusto/api/connection-strings/storage.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#76 Corrects on-premises in vnet-create-cluster-portal
  data-explorer/vnet-create-cluster-portal.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#80 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/controlling-tracing.md
  data-explorer/kusto/api/netfx/kusto-ingest-best-practices.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-errors.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-permissions.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-rest.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-status.md
  data-explorer/kusto/api/netfx/request-properties.md
  data-explorer/kusto/api/powershell/powershell.md
  data-explorer/kusto/api/tds/sqlknownissues.md
  data-explorer/kusto/concepts/crossclusterandschemachanges.md
  data-explorer/kusto/concepts/resulttruncation.md
  data-explorer/kusto/management/access-control/aad.md
  data-explorer/kusto/management/access-control/how-to-authenticate-with-aad.md
  data-explorer/kusto/management/data-ingestion/ingest-from-query.md
  data-explorer/kusto/management/data-ingestion/ingest-from-storage.md
  data-explorer/kusto/management/streamingingestion-policy.md
Labels: do-not-merge

#83 Fix git push error for protected CLA branch
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/usinghlltdigest.md
  data-explorer/kusto/query/whereoperator.md
Labels: do-not-merge

#87 Fix git push error for protected CLA branch
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/toc.yml
Labels: do-not-merge

#89 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/request-properties.md
  data-explorer/kusto/api/tds/index.md
  data-explorer/kusto/management/extents-commands.md
  data-explorer/kusto/query/array_shift_rightfunction.md
  data-explorer/kusto/query/batches.md
  data-explorer/kusto/query/current-principal-ismemberoffunction.md
  data-explorer/kusto/query/dcount-hllfunction.md
  data-explorer/kusto/query/isnullfunction.md
  data-explorer/kusto/query/make-seriesoperator.md
  data-explorer/kusto/query/mvexpandoperator.md
  data-explorer/kusto/query/schema-entities/tables.md
  data-explorer/kusto/query/series-fit-2linesfunction.md
  data-explorer/kusto/query/session-count-plugin.md
  data-explorer/kusto/query/tointfunction.md
  data-explorer/kusto/query/windowsfunctions.md
  data-explorer/toc.yml
Labels: do-not-merge

#90 Fix git push error for protected CLA branch
  data-explorer/kusto/management/show-table-schema-command.md
Labels: do-not-merge

#93 Fix git push error for protected CLA branch
  data-explorer/kusto/api/images/about-kusto-ingest/direct-ingest.png
  data-explorer/kusto/api/images/about-kusto-ingest/queued-ingest.png
  data-explorer/kusto/api/images/direct-ingest.jpg
  data-explorer/kusto/api/images/host-web-ux-in-iframe/web-ux.png
  data-explorer/kusto/api/images/kusto-ingest-client-permissions/direct-ingest.png
  data-explorer/kusto/api/images/kusto-ingest-client-permissions/queued-ingest.png
  data-explorer/kusto/api/images/linkedserver/LinkedServerConnection.png
  data-explorer/kusto/api/images/linkedserver/LinkedServerLogin.png
  data-explorer/kusto/api/images/queued-ingest.jpg
  data-explorer/kusto/api/images/response/rest-json-representation.png
  data-explorer/kusto/api/images/web-ux.jpg
  data-explorer/kusto/api/monaco/host-web-ux-in-iframe.md
  data-explorer/kusto/api/netfx/about-kusto-ingest.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-permissions.md
  data-explorer/kusto/tools/images/KustoTools-LogicApp/logicapp-blanktemplate.png
  data-explorer/kusto/tools/images/KustoTools-LogicApp/logicapp-editdesigner.png
  data-explorer/kusto/tools/images/logicapps/logicapp-add.png
  data-explorer/kusto/tools/images/logicapps/logicapp-blanktemplate.png
  data-explorer/kusto/tools/images/logicapps/logicapp-create-new.png
  data-explorer/kusto/tools/images/logicapps/logicapp-createlogicapp.png
  data-explorer/kusto/tools/images/logicapps/logicapp-editdesigner.png
  data-explorer/kusto/tools/images/logicapps/logicapp-kustoconnector.png
  data-explorer/kusto/tools/images/logicapps/logicapp-search.png
  data-explorer/kusto/tools/logicapps.md
  data-explorer/toc.yml
Labels: do-not-merge

#88 Old mapping syntax has been deprecated
  data-explorer/end-to-end-csharp.md
  data-explorer/ingest-data-no-code.md
  data-explorer/ingest-json-formats.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-reference.md
  data-explorer/kusto/api/netfx/kusto-ingest-queued-ingest-sample.md
  data-explorer/kusto/management/mappings.md
  data-explorer/net-standard-ingest-data.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, ready-to-merge

#95 Updating dayofweekfunction documentation
  data-explorer/kusto/query/dayofweekfunction.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#96 Fix git push error for protected CLA branch
  data-explorer/manage-cluster-choose-sku.md
Labels: do-not-merge

#97 Fix git push error for protected CLA branch
  data-explorer/kusto/api/netfx/kusto-ingest-client-examples.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-reference.md
Labels: do-not-merge

#100 Fix git push error for protected CLA branch
  data-explorer/manage-cluster-horizontal-scaling.md
Labels: do-not-merge

#103 Fix git push error for protected CLA branch
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/management/mergepolicy.md
Labels: do-not-merge

#99 Update Kusto connection strings docs
  data-explorer/kusto/api/connection-strings/kusto.md
Labels: Change sent to author, aq-pr-triaged, data-explorer/svc, ready-to-merge

#105 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/connect-from-databricks.md
  data-explorer/data-share.md
  data-explorer/ingest-data-overview.md
  data-explorer/kusto/api/netfx/kusto-ingest-client-reference.md
  data-explorer/kusto/api/rest/deeplink.md
  data-explorer/kusto/concepts/index.md
  data-explorer/kusto/management/data-ingestion/index.md
  data-explorer/kusto/management/external-sql-tables.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/management/mergepolicy.md
  data-explorer/kusto/management/rowlevelsecuritypolicy.md
  data-explorer/kusto/query/broadcastjoin.md
  data-explorer/kusto/query/cross-cluster-or-database-queries.md
  data-explorer/kusto/query/joincrosscluster.md
  data-explorer/kusto/query/schema-entities/externaltables.md
  data-explorer/kusto/query/sethaselementfunction.md
  data-explorer/kusto/tools/images/kusto-explorer-troubleshooting/clickonce-err-1.png
  data-explorer/kusto/tools/images/kusto-explorer-using/add-authorized-principals-window.png
  data-explorer/kusto/tools/images/kusto-explorer-using/basic-query.png
  data-explorer/kusto/tools/images/kusto-explorer-using/confirm-add-authorized-principals.png
  data-explorer/kusto/tools/images/kusto-explorer-using/confirm-drop-authorized-principals.png
  data-explorer/kusto/tools/images/kusto-explorer-using/manage-authorized-principals-window.png
  data-explorer/kusto/tools/images/kusto-explorer-using/menu-export.png
  data-explorer/kusto/tools/images/kusto-explorer-using/parametrized-query-1.png
  data-explorer/kusto/tools/images/kusto-explorer-using/parametrized-query-2.png
  data-explorer/kusto/tools/images/kusto-explorer-using/parametrized-query-3.png
  data-explorer/kusto/tools/images/kusto-explorer-using/parametrized-query-4.png
  data-explorer/kusto/tools/images/kusto-explorer-using/parametrized-query-5.png
  data-explorer/kusto/tools/images/kusto-explorer-using/right-click-manage-authorized-principals.png
  data-explorer/kusto/tools/images/kusto-explorer-using/search-plus-plus-results.png
  data-explorer/kusto/tools/images/kusto-explorer-using/search-plus-plus.png
  data-explorer/kusto/tools/images/kusto-explorer-using/share-results-2.png
  data-explorer/kusto/tools/images/kusto-explorer/advanced-connection-string.png
  data-explorer/kusto/tools/images/kusto-explorer/connections-panel.png
  data-explorer/kusto/tools/images/kusto-explorer/connections-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/file-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/help-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/home-query-menu.png
  data-explorer/kusto/tools/images/kusto-explorer/home-share-menu.png
  data-explorer/kusto/tools/images/kusto-explorer/home-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/home-view-menu.png
  data-explorer/kusto/tools/images/kusto-explorer/home-visualizations-menu.png
  data-explorer/kusto/tools/images/kusto-explorer/ke-color-scheme.png
  data-explorer/kusto/tools/images/kusto-explorer/ke-start.png
  data-explorer/kusto/tools/images/kusto-explorer/management-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/monitoring-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/tools-tab.png
  data-explorer/kusto/tools/images/kusto-explorer/view-tab.png
  data-explorer/kusto/tools/kusto-explorer-troubleshooting.md
  data-explorer/kusto/tools/kusto-explorer-using.md
  data-explorer/kusto/tools/kusto-explorer.md
  data-explorer/media/data-ingestion-overview/data-management-and-ingestion-overview.png
  data-explorer/media/data-share/adx-datashare-image.png
  data-explorer/toc.yml
Labels: do-not-merge

#108 Fix git push error for protected CLA branch
  data-explorer/azure-data-explorer-dashboards.md
  data-explorer/kusto/management/externaltables.md
  data-explorer/kusto/management/merge-policy.md
  data-explorer/kusto/management/mergepolicy.md
  data-explorer/kusto/query/schema-entities/externaltables.md
  data-explorer/media/adx-dashboards/add-visual.png
  data-explorer/media/adx-dashboards/dash.png
  data-explorer/media/adx-dashboards/data-source-pane.png
  data-explorer/media/adx-dashboards/data-source.png
  data-explorer/media/adx-dashboards/empty-dashboard-new-query.png
  data-explorer/media/adx-dashboards/initial-query.png
  data-explorer/media/adx-dashboards/new-dashboard-popup.png
  data-explorer/media/adx-dashboards/new-dashboard.png
  data-explorer/media/adx-dashboards/parameter-pane.png
  data-explorer/media/adx-dashboards/parameters.png
  data-explorer/media/adx-dashboards/save-dashboard.png
  data-explorer/toc.yml
Labels: do-not-merge

#111 Fix git push error for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/ingestion-properties.md
  data-explorer/kusto/management/access-control/how-to-provision-aad-app.md
  data-explorer/kusto/management/calloutpolicy.md
  data-explorer/kusto/management/capacitypolicy.md
  data-explorer/kusto/management/commands.md
  data-explorer/kusto/management/create-merge-tables-command.md
  data-explorer/kusto/management/data-export/index.md
  data-explorer/kusto/management/ingestionfailures.md
  data-explorer/kusto/management/operations.md
  data-explorer/kusto/management/retentionpolicy.md
  data-explorer/kusto/management/shardingpolicy.md
  data-explorer/kusto/management/tables.md
  data-explorer/kusto/query/externaldata-operator.md
  data-explorer/kusto/query/usinghlltdigest.md
  data-explorer/toc.yml
Labels: do-not-merge

#112 Fix git push error for protected CLA branch
  data-explorer/kusto/management/partitioningpolicy.md
Labels: do-not-merge

#120 Fix git push error for protected CLA branch
  data-explorer/kusto/query/active-users-count-plugin.md
  data-explorer/kusto/query/sqlrequestplugin.md
Labels: do-not-merge

#121 Fix git push error for protected CLA branch
  data-explorer/write-queries.md
Labels: do-not-merge
