Repository MicrosoftDocs/dataexplorer-docs, pull requests merged in 2022-11, with the labels that each got.

#1482 Repo sync for protected CLA branch
  data-explorer/data-explorer-insights.md
  data-explorer/kusto/management/alter-capacity-policy-command.md
  data-explorer/kusto/management/partitioningpolicy.md
  data-explorer/kusto/query/abs-function.md
  data-explorer/kusto/query/acosfunction.md
  data-explorer/kusto/query/active-users-count-plugin.md
  data-explorer/kusto/query/activity-counts-metrics-plugin.md
  data-explorer/kusto/query/activity-engagement-plugin.md
  data-explorer/kusto/query/activity-metrics-plugin.md
  data-explorer/kusto/query/aggregation-functions.md
  data-explorer/kusto/query/agofunction.md
  data-explorer/kusto/query/arg-max-aggfunction.md
  data-explorer/kusto/query/arg-min-aggfunction.md
  data-explorer/kusto/query/around-function.md
  data-explorer/kusto/query/atanfunction.md
  data-explorer/kusto/query/autoclusterplugin.md
  data-explorer/kusto/query/avg-aggfunction.md
  data-explorer/kusto/query/avgif-aggfunction.md
  data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md
  data-explorer/kusto/query/bag-has-key-function.md
  data-explorer/kusto/query/bag-merge-function.md
  data-explorer/kusto/query/bag-remove-keys-function.md
  data-explorer/kusto/query/bag-unpackplugin.md
  data-explorer/kusto/query/bagkeysfunction.md
  data-explorer/kusto/query/base64_decode_toarrayfunction.md
  data-explorer/kusto/query/base64_decode_tostringfunction.md
  data-explorer/kusto/query/base64_encode_fromarrayfunction.md
  data-explorer/kusto/query/count-distinct-aggfunction.md
  data-explorer/kusto/query/count-distinctif-aggfunction.md
  data-explorer/kusto/query/makeset-aggfunction.md
  data-explorer/kusto/query/nowfunction.md
  data-explorer/kusto/query/timezone.md
  data-explorer/kusto/query/toc.yml
  data-explorer/toc.yml
Labels: do-not-merge, CLA

#1483 Repo sync for protected CLA branch
  data-explorer/kusto/management/rowlevelsecuritypolicy.md
  data-explorer/kusto/query/topnestedoperator.md
Labels: do-not-merge, CLA

#1487 Repo sync for protected CLA branch
  data-explorer/kusto/query/arg-max-aggfunction.md
  data-explorer/kusto/query/avgif-aggfunction.md
  data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md
  data-explorer/kusto/query/bag-has-key-function.md
  data-explorer/kusto/query/bag-merge-function.md
  data-explorer/kusto/query/bag-remove-keys-function.md
  data-explorer/kusto/query/bag-unpackplugin.md
  data-explorer/kusto/query/bagkeysfunction.md
  data-explorer/kusto/query/base64_decode_toarrayfunction.md
  data-explorer/kusto/query/base64_decode_tostringfunction.md
  data-explorer/kusto/query/base64_encode_fromarrayfunction.md
  data-explorer/kusto/query/base64_encode_tostringfunction.md
  data-explorer/kusto/query/datetime-partfunction.md
  data-explorer/kusto/query/extractallfunction.md
  data-explorer/kusto/query/isnotnullfunction.md
  data-explorer/kusto/query/parseurlqueryfunction.md
  data-explorer/kusto/query/toc.yml
  data-explorer/kusto/query/totimespanfunction.md
Labels: do-not-merge, CLA

#1442 Update predict-fl.md
  data-explorer/kusto/functions-library/predict-fl.md
Labels: Change sent to author, data-explorer/svc, do-not-merge, aq-pr-triaged

#1486 Update drop-extents.md
  data-explorer/kusto/management/drop-extents.md
Labels: Change sent to author, data-explorer/svc, do-not-merge

#1491 Repo sync for protected CLA branch
  data-explorer/ingest-data-no-code.md
  data-explorer/kusto/management/managed-identity-policy.md
  data-explorer/kusto/management/materialized-views/materialized-view-policies.md
  data-explorer/kusto/management/materialized-views/materialized-view-purge.md
  data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md
  data-explorer/kusto/query/geo-polygon-to-s2cells-function.md
  data-explorer/kusto/query/makeset-aggfunction.md
  data-explorer/kusto/query/pythonplugin.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/take-any-aggfunction.md
  data-explorer/kusto/query/take-anyif-aggfunction.md
  data-explorer/managed-identities-overview.md
  data-explorer/whats-new-archive.md
  data-explorer/whats-new.md
  data-explorer/write-queries.md
Labels: do-not-merge, CLA

#1492 Repo sync for protected CLA branch
  data-explorer/data-share.md
  data-explorer/kusto/api/netfx/request-properties.md
  data-explorer/kusto/query/cosmosdb-plugin.md
  data-explorer/kusto/query/cursorcurrent.md
  data-explorer/kusto/query/isnotemptyfunction.md
  data-explorer/kusto/query/re2.md
  data-explorer/kusto/query/reduceoperator.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/series-ceiling-function.md
  data-explorer/kusto/query/series-floor-function.md
  data-explorer/kusto/query/series-log-function.md
  data-explorer/kusto/query/splunk-cheat-sheet.md
  data-explorer/kusto/query/toc.yml
  data-explorer/kusto/query/weekofyearfunction.md
Labels: do-not-merge, CLA

#1493 Repo sync for protected CLA branch
  data-explorer/kusto/api/connection-strings/kusto.md
  data-explorer/kusto/management/materialized-views/materialized-view-create.md
  data-explorer/kusto/management/materialized-views/materialized-view-overview.md
  data-explorer/kusto/management/materialized-views/materialized-views-limitations.md
  data-explorer/kusto/management/toc.yml
  data-explorer/kusto/query/autoclusterplugin.md
  data-explorer/kusto/query/azure-digital-twins-query-request-plugin.md
  data-explorer/kusto/query/bag-unpackplugin.md
  data-explorer/kusto/query/base64-decode-toguid-function.md
  data-explorer/kusto/query/base64-encode-fromguid-function.md
  data-explorer/kusto/query/base64_encode_tostringfunction.md
  data-explorer/kusto/query/basketplugin.md
  data-explorer/kusto/query/beta-cdffunction.md
  data-explorer/kusto/query/beta-invfunction.md
  data-explorer/kusto/query/beta-pdffunction.md
Labels: do-not-merge, CLA

#1494 Repo sync for protected CLA branch
  data-explorer/ingest-data-no-code.md
  data-explorer/kusto/functions-library/series-lag-fl.md
  data-explorer/kusto/management/materialized-views/materialized-view-policies.md
  data-explorer/kusto/management/materialized-views/materialized-view-purge.md
  data-explorer/kusto/query/geo-polygon-to-s2cells-function.md
  data-explorer/kusto/query/makelist-aggfunction.md
  data-explorer/kusto/query/makeset-aggfunction.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/summarizeoperator.md
  data-explorer/kusto/query/take-any-aggfunction.md
  data-explorer/write-queries.md
Labels: do-not-merge, CLA

#1499 Repo sync for protected CLA branch
  data-explorer/data-connection-event-hub-csharp.md
  data-explorer/data-connection-event-hub-python.md
  data-explorer/data-connection-event-hub-resource-manager.md
  data-explorer/event-hub-wizard.md
  data-explorer/includes/data-connection-auth.md
  data-explorer/includes/event-hub-connection-caution.md
  data-explorer/index.yml
  data-explorer/ingest-data-event-hub.md
  data-explorer/ingest-data-iot-hub.md
  data-explorer/kusto/functions-library/series-lag-fl.md
  data-explorer/kusto/management/databasecursor.md
  data-explorer/kusto/query/arg-max-aggfunction.md
  data-explorer/kusto/query/arg-min-aggfunction.md
  data-explorer/kusto/query/arraylengthfunction.md
  data-explorer/kusto/query/columnifexists.md
  data-explorer/kusto/query/extentidfunction.md
  data-explorer/kusto/query/isnotemptyfunction.md
  data-explorer/kusto/query/parseurlfunction.md
  data-explorer/kusto/query/replace-regex-function.md
  data-explorer/kusto/query/replace-string-function.md
  data-explorer/kusto/query/samples.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/toc.yml
  data-explorer/kusto/query/weekofyearfunction.md
  data-explorer/media/ingest-data-iot-hub/add-data-connection.png
  data-explorer/media/ingest-data-iot-hub/create-data-connection.png
  data-explorer/media/ingest-data-iot-hub/data-connection-pane.png
  data-explorer/media/ingest-data-iot-hub/default-routing-settings.png
  data-explorer/media/ingest-data-iot-hub/iot-hub-connection.png
  data-explorer/media/ingest-data-iot-hub/table-routing-settings.png
  data-explorer/query-monitor-data.md
  data-explorer/toc.yml
Labels: do-not-merge, CLA

#1495 Update about-kusto-data.md
  data-explorer/kusto/api/netfx/about-kusto-data.md
Labels: Change sent to author, data-explorer/svc, do-not-merge, aq-pr-triaged

#1503 Repo sync for protected CLA branch
  data-explorer/kusto/query/bin-autofunction.md
  data-explorer/kusto/query/binary-shift-leftfunction.md
  data-explorer/kusto/query/binary-shift-rightfunction.md
  data-explorer/kusto/query/binary-xorfunction.md
  data-explorer/kusto/query/binatfunction.md
  data-explorer/kusto/query/binfunction.md
  data-explorer/kusto/query/bitset-count-onesfunction.md
  data-explorer/kusto/query/buildschema-aggfunction.md
  data-explorer/kusto/query/casefunction.md
  data-explorer/kusto/query/ceilingfunction.md
  data-explorer/kusto/query/renderoperator.md
Labels: do-not-merge, CLA

#1504 Repo sync for protected CLA branch
  data-explorer/kusto/management/updatepolicy.md
Labels: Change sent to author, data-explorer/svc, do-not-merge, CLA

#1505 Repo sync for protected CLA branch
  .openpublishing.redirection.json
  data-explorer/ingest-data-event-hub-overview.md
  data-explorer/kusto/management/data-export/create-alter-continuous.md
  data-explorer/kusto/query/makestringfunction.md
  data-explorer/kusto/query/toc.yml
  data-explorer/kusto/query/toutf8function.md
  data-explorer/kusto/query/unicode-codepoints-from-string-function.md
  data-explorer/kusto/query/unicode-codepoints-to-string-function.md
  data-explorer/using-metrics.md
Labels: do-not-merge, CLA

#1506 Repo sync for protected CLA branch
  data-explorer/ingest-data-iot-hub-overview.md
Labels: do-not-merge, CLA

#1507 Repo sync for protected CLA branch
  data-explorer/kusto/query/avgif-aggfunction.md
  data-explorer/kusto/query/betweenoperator.md
  data-explorer/kusto/query/bin-autofunction.md
  data-explorer/kusto/query/binary-all-and-aggfunction.md
  data-explorer/kusto/query/binary-all-or-aggfunction.md
  data-explorer/kusto/query/binary-all-xor-aggfunction.md
  data-explorer/kusto/query/binary-andfunction.md
  data-explorer/kusto/query/binary-notfunction.md
  data-explorer/kusto/query/binary-orfunction.md
  data-explorer/kusto/query/binary-shift-leftfunction.md
  data-explorer/kusto/query/binary-shift-rightfunction.md
  data-explorer/kusto/query/binary-xorfunction.md
  data-explorer/kusto/query/binatfunction.md
  data-explorer/kusto/query/binfunction.md
  data-explorer/kusto/query/bitset-count-onesfunction.md
  data-explorer/kusto/query/buildschema-aggfunction.md
  data-explorer/kusto/query/casefunction.md
  data-explorer/kusto/query/ceilingfunction.md
  data-explorer/kusto/query/clusterfunction.md
  data-explorer/kusto/query/coalescefunction.md
  data-explorer/kusto/query/columnifexists.md
  data-explorer/kusto/query/consumeoperator.md
  data-explorer/kusto/query/contains-cs-operator.md
  data-explorer/kusto/query/contains-operator.md
  data-explorer/kusto/query/convert-angle-function.md
  data-explorer/kusto/query/convert-energy-function.md
  data-explorer/kusto/query/convert-force-function.md
  data-explorer/kusto/query/convert-length-function.md
  data-explorer/kusto/query/convert-mass-function.md
  data-explorer/kusto/query/convert-speed-function.md
  data-explorer/kusto/query/convert-temperature-function.md
  data-explorer/kusto/query/convert-volume-function.md
  data-explorer/kusto/query/cosfunction.md
  data-explorer/kusto/query/cosmosdb-plugin.md
  data-explorer/kusto/query/cotfunction.md
  data-explorer/kusto/query/count-aggfunction.md
  data-explorer/kusto/query/countif-aggfunction.md
  data-explorer/kusto/query/countoffunction.md
  data-explorer/kusto/query/countoperator.md
  data-explorer/kusto/query/current-cluster-endpoint-function.md
  data-explorer/kusto/query/current-database-function.md
  data-explorer/kusto/query/current-principal-detailsfunction.md
  data-explorer/kusto/query/dcountif-aggfunction.md
  data-explorer/kusto/query/make-bag-if-aggfunction.md
  data-explorer/kusto/query/makelistif-aggfunction.md
  data-explorer/kusto/query/makesetif-aggfunction.md
  data-explorer/kusto/query/maxif-aggfunction.md
  data-explorer/kusto/query/minif-aggfunction.md
  data-explorer/kusto/query/stdevif-aggfunction.md
  data-explorer/kusto/query/varianceif-aggfunction.md
Labels: do-not-merge, CLA

#1510 Repo sync for protected CLA branch
  data-explorer/kusto/functions-library/functions-library.md
  data-explorer/kusto/functions-library/images/series-mv-ee-anomalies-fl/mv-ee-anomalies-sample-data.png
  data-explorer/kusto/functions-library/images/series-mv-ee-anomalies-fl/mv-ee-anomalies-scatter-chart.png
  data-explorer/kusto/functions-library/images/series-mv-ee-anomalies-fl/mv-ee-anomalies-time-chart.png
  data-explorer/kusto/functions-library/images/series-mv-if-anomalies-fl/mv-if-anomalies-scatter-chart.png
  data-explorer/kusto/functions-library/images/series-mv-if-anomalies-fl/mv-if-anomalies-time-chart.png
  data-explorer/kusto/functions-library/images/series-mv-oc-anomalies-fl/mv-oc-anomalies-scatter-chart.png
  data-explorer/kusto/functions-library/images/series-mv-oc-anomalies-fl/mv-oc-anomalies-time-chart.png
  data-explorer/kusto/functions-library/series-mv-ee-anomalies-fl.md
  data-explorer/kusto/functions-library/series-mv-if-anomalies-fl.md
  data-explorer/kusto/functions-library/series-mv-oc-anomalies-fl.md
  data-explorer/time-series-analysis.md
  data-explorer/toc.yml
Labels: do-not-merge, CLA

#1515 Repo sync for protected CLA branch
  data-explorer/azure-advisor.md
  data-explorer/ingest-data-event-hub.md
  data-explorer/kusto/management/execute-database-script.md
  data-explorer/kusto/query/functions/user-defined-functions.md
  data-explorer/kusto/query/ipv4-comparefunction.md
  data-explorer/kusto/query/ipv4-is-in-any-range-function.md
  data-explorer/kusto/query/ipv4-is-in-range-function.md
  data-explorer/kusto/query/ipv4-is-matchfunction.md
  data-explorer/kusto/query/ipv4-is-privatefunction.md
  data-explorer/kusto/query/ipv4-lookup-plugin.md
  data-explorer/kusto/query/ipv4-netmask-suffix-function.md
  data-explorer/kusto/query/ipv6-comparefunction.md
  data-explorer/kusto/query/ipv6-is-in-any-range-function.md
  data-explorer/kusto/query/ipv6-is-in-range-function.md
  data-explorer/kusto/query/ipv6-is-matchfunction.md
  data-explorer/kusto/query/parse-ipv4function.md
  data-explorer/kusto/query/parse-ipv6-maskfunction.md
  data-explorer/kusto/query/parse-ipv6function.md
  data-explorer/kusto/query/restrictstatement.md
  data-explorer/kusto/query/scalarfunctions.md
  data-explorer/kusto/query/toc.yml
Labels: do-not-merge, CLA

#1517 Repo sync for protected CLA branch
  data-explorer/dashboard-customize-visuals.md
  data-explorer/data-factory-load-data.md
  data-explorer/includes/data-mapping-overview.md
  data-explorer/includes/data-mapping-type-note.md
  data-explorer/kusto/management/alter-merge-table-command.md
  data-explorer/kusto/management/avro-mapping.md
  data-explorer/kusto/management/csv-mapping.md
  data-explorer/kusto/management/external-tables-azurestorage-azuredatalake.md
  data-explorer/kusto/management/includes/data-mapping-overview.md
  data-explorer/kusto/management/json-mapping.md
  data-explorer/kusto/management/mappings.md
  data-explorer/kusto/management/orc-mapping.md
  data-explorer/kusto/management/parquet-mapping.md
  data-explorer/kusto/management/toc.yml
  data-explorer/kusto/management/w3c-log-file-mapping.md
  data-explorer/kusto/query/arrayslicefunction.md
  data-explorer/kusto/query/arraysortascfunction.md
  data-explorer/kusto/query/arraysortdescfunction.md
  data-explorer/kusto/query/arraysplitfunction.md
  data-explorer/kusto/query/asinfunction.md
  data-explorer/kusto/query/asoperator.md
  data-explorer/kusto/query/assert-function.md
  data-explorer/kusto/query/atan2function.md
  data-explorer/kusto/query/atanfunction.md
  data-explorer/kusto/query/avg-aggfunction.md
  data-explorer/kusto/query/summarizeoperator.md
  data-explorer/manage-cluster-vertical-scaling.md
  data-explorer/media/dashboard-customize-visuals/add-conditional-formatting.png
  data-explorer/media/dashboard-customize-visuals/color-by-condition.png
  data-explorer/media/dashboard-customize-visuals/color-by-value-results.png
  data-explorer/media/dashboard-customize-visuals/color-by-value.png
  data-explorer/media/dashboard-customize-visuals/edit-conditional-formatting.png
  data-explorer/media/dashboard-customize-visuals/edit-new-rule.png
  data-explorer/media/dashboard-customize-visuals/edit-tile.png
  data-explorer/media/dashboard-customize-visuals/enter-editing-mode.png
  data-explorer/media/dashboard-customize-visuals/save-changes-dashboard.png
  data-explorer/media/manage-cluster-vertical-scaling/scale-up.png
Labels: do-not-merge, CLA

#1518 Repo sync for protected CLA branch
  data-explorer/docfx.json
  data-explorer/kusto/query/abs-function.md
  data-explorer/kusto/query/acosfunction.md
  data-explorer/kusto/query/active-users-count-plugin.md
  data-explorer/kusto/query/activity-counts-metrics-plugin.md
  data-explorer/kusto/query/activity-engagement-plugin.md
  data-explorer/kusto/query/activity-metrics-plugin.md
  data-explorer/kusto/query/agofunction.md
  data-explorer/kusto/query/arg-max-aggfunction.md
  data-explorer/kusto/query/arg-min-aggfunction.md
  data-explorer/kusto/query/around-function.md
Labels: do-not-merge, CLA

#1519 Repo sync for protected CLA branch
  data-explorer/kusto/management/show-database.md
  data-explorer/kusto/management/show-table-details-command.md
Labels: do-not-merge, CLA
